version: "3.8"

services:
  setup:
    build:
      context: .
    image: task_list_app_api_prod_setup:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: production
      DATABASE_URL: "mysql2://root:${DB_PASSWORD}@db:3306/task_list_app_api_production"
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DB_PASSWORD: ${DB_PASSWORD}
    command: bash -c "bundle exec rails db:create db:migrate db:seed"

  app:
    build:
      context: .
    image: task_list_app_api_prod:latest
    container_name: task_list_app_api_prod
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      DATABASE_URL: "mysql2://root:${DB_PASSWORD}@db:3306/task_list_app_api_production"
      REDIS_URL: "redis://redis:6379/0"
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
      - redis
    command: bundle exec rails server -b 0.0.0.0 -p 3000

  clockwork:
    build:
      context: .
    image: task_list_app_api_prod_clockwork:latest
    container_name: task_list_app_api_prod_clockwork
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      - redis
      - db
    environment:
      RAILS_ENV: production
      REDIS_URL: "redis://redis:6379/0"
      DATABASE_URL: "mysql2://root:${DB_PASSWORD}@db:3306/task_list_app_api_production"
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DB_PASSWORD: ${DB_PASSWORD}
    command: bundle exec clock

  db:
    image: mysql:8.0
    container_name: task_list_app_api_prod_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: task_list_app_api_production
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: task_list_app_api_prod_redis

  # nginx:
  #   image: nginx:latest
  #   container_name: task_list_app_api_prod_nginx
  #   depends_on:
  #     - app
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   volumes:
  #     - ./ssl:/etc/nginx/ssl:ro
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data:
  bundle_cache:
