default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "root") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
  host: <%= ENV.fetch("DATABASE_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DATABASE_PORT", "3306") %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: task_list_app_api_development

test:
  <<: *default
  database: task_list_app_api_test

production:
  <<: *default
  database: task_list_app_api_production
